### ISSUE TITLE
get_follow_count return wrong results for api.steemitdev.com

### ISSUE THREAD

**Issue by mvandeberg** [steemit/hivemind#157]
From steemit/steem#3192

> I test API `get_follow_count` for _**api.steemitdev.com**_ and _**api.steemit.com.**_
> 
> JSON message:
> `{"jsonrpc": "2.0", "method": "condenser_api.get_follow_count", "params": ["oflyhigh"], "id": 1}`
> 
> The _**api.steemit.com**_ return right results:
> 
> ```
> {'id': 1,
>  'jsonrpc': '2.0',
>  'result': {'account': 'oflyhigh',
>             'follower_count': 8465,
>             'following_count': 134}}
> ```
> But the results from _**api.steemitdev.com**_ are totally wrong.
> 
> ```
> {'id': 1,
>  'jsonrpc': '2.0',
>  'result': {'account': 'oflyhigh',
>             'follower_count': 725,
>             'following_count': -5}}
> ```
> I think it might be caused by [Upcoming Changes to api.steemit.com](https://steemit.com/steemit/@steemitdev/upcoming-changes-to-api-steemit-com) & hivemind.
> 
> Hope this issue can be fixed before we do routing select steemd methods directly to hivemind.

**Comment by roadscape** [comment]
Thanks for the report @oflyhigh. This is most likely an artifact of a previous follows bug; will add a migration which forces a recount.
