### ISSUE TITLE
active_votes: inconsistent rep and missing time

### ISSUE THREAD

**Issue by crokkon** [steemit/hivemind#161]
I guess this was intended as a feature, but is there any chance to go back to providing the raw author reputation values everywhere instead of the normalized/log10 values?

steemit node:
```
curl -s --data '{"method": "tags_api.get_discussion", "params": {"author": "steemitboard", "permlink": "steemitboard-notify-stmdev-20181024t002841000z"}, "jsonrpc": "2.0", "id": 2}' https://api.steemit.com
[...] "active_votes":[{"voter":"stmdev","reputation":"59.5","percent":"10000","rshares":"0"}],"author_reputation":20209499381910, [...]
```
* reputation in `active_votes` is the log10 value
* `author_reputation` is the raw value
* voting time and weight is completely missing

minnowsupport node:
```
curl -s --data '{"method": "tags_api.get_discussion", "params": {"author": "steemitboard", "permlink": "steemitboard-notify-stmdev-20181024t002841000z"}, "jsonrpc": "2.0", "id": 2}' https://steemd.minnowsupportproject.org
[...],"active_votes":[{"voter":"stmdev","weight":0,"rshares":0,"percent":10000,"reputation":"7203258450054","time":"2018-11-11T10:33:09"}],"replies":[],"author_reputation":"23856299575939"[...]
```
(reputation in `active_votes` is the raw value and `author_reputation` is the raw value, voting time is available).

Providing the log10 values at *some* places makes it much harder to write code that works with any node and the single-digit precision makes it harder to see the reputation difference between voter and author relevant for flags.

**Comment by roadscape** [comment]
These condenser_api calls are supposed to convert rep back to raw even though it's normalized internally. This is a bug and needs to be fixed.

As for voting time and weight -- these contribute to an already huge response (for both post lists and threads). Generally the backend needs to move towards more lightweight responses, and the client should make explicit calls (e.g. `get_active_votes`) for detailed data when needed.

**Comment by emre** [comment]
Seems like the raw reputation is explicitly set to a normalized value while indexing.

https://github.com/steemit/hivemind/blob/master/hive/utils/post.py#L116.

**Comment by roadscape** [comment]
PR to fix returned reputation: https://github.com/steemit/hivemind/pull/225
