### ISSUE TITLE
Hive sync crashes on block 28,746,072

### ISSUE THREAD

**Issue by jrawsthorne** [steemit/hivemind#162]
Block 28,746,072 contains a [reblog transaction](https://steemd.com/tx/a6064b727de9065d15b814ccd51106c5fa0e47fe) which contains the custom json:
```json

"["reblog",{"account" : "zhangp","auther" : "zyyy","permlink" : "wherein-1545359414"}]"
```
Author is spelled auther therefore this code throws an exception (KeyError)
https://github.com/steemit/hivemind/blob/40afe61302fede598f782c92e6ef2a7581ef9933/hive/indexer/custom_op.py#L72

**Comment by inertia186** [comment]
Observed on my node as well.
