### ISSUE TITLE
get_follow_count returns wrong value and get_followxxx returns chronologically

### ISSUE THREAD

**Issue by economicstudio** [steemit/hivemind#167]
Maybe there is some migration going on now (related to https://steemit.com/steemit/@steemitdev/upcoming-changes-to-api-steemit-com), but currently

- there are some accounts that get_follow_count returns the wrong value, e.g., https://steemit.com/@bukio/followed (38 but it should be zero) (I also checked with API call, so not UI problem.)

- get_followers/ing return the results chronologically 
should better return alphabetically as before (unless the change is notified very clearly) I believe in hive this will be an easy fix.

**Comment by economicstudio** [comment]
Hi @roadscape Thank you for your comment. It seems you temporarily rolled back, so everything's normal now.

For the order of follow, one problem of chronological order is, I think, privacy. Of course, it's blockchain, so everything's public. But you know follow is custom json, so it's relatively hidden :) in some sense. I'm pretty sure that most people don't prefer chronological order :) (I agree that it's informative in some sense, I also enjoyed watching it, who followed me recently.)

ps. Could you follow me if you don't mind? My steemit id is blockchainstudio. You already follow many, why not one more, who is a kind unpaid contributor :) Thanks!

**Comment by roadscape** [comment]
Invalid counts fixed in https://github.com/steemit/hivemind/pull/163/commits/4c013ef84f3cdf56e043cf4adf9d0829128e2674
