### ISSUE TITLE
trending tag order

### ISSUE THREAD

**Issue by economicstudio** [steemit/hivemind#168]
This also happened before briefly, so I guess there is migration process going on now. #167 

`get_trending_tags` shows in the order of payout, which may not be intended nor desired.

**Comment by roadscape** [comment]
I'm not sure there's a more appropriate sort order, since the definition of a trending tag is how much total pending payouts it has.

**Comment by economicstudio** [comment]
I agree. So it's entirely up to STINC. I guess there are pros and cons. Sorting by payout is a good indicator unless there is "abusing," or good to detect it. also good to make dapps compete each other :) but maybe some people feel too much "unequal" payout, which I personally think important. I worked for facebook before, and they cared about those emotional things a lot. Maybe Steemit is quite different, but I saw many users without good payout for first few weeks just leave. Also if I remember correctly, the new sorting criteria is by payout of (posts+comments). Another problem is, for instance, utopian is very special one, but ranked too high with that criteria. Steemhunt as well. How many people actually use or read them? Probably not many (while utopian is very important). But I agree. what is a good ranking algorithm? really difficult problem :)

ps. Thanks a lot, by the way :) Actually, one more thing. I asked this before, but is there any plan to update official steem-python library? I know it isn't urgent at all, but hope it's in the utopian whitelist so that at least users would update more actively. While beem is good, still I prefer official in many cases. Many thanks!

**Comment by roadscape** [comment]
Tag organization definitely needs some work, and the current implementation is just a lightly simplified version of steemd's. Generally though, since there are no rules around tag usage, the results are of limited insight. Open to suggestions & PR's. WRT `steem-python`, it should support hivemind already; if not, please file an issue on that repo.
