### ISSUE TITLE
api.steemit.com reports invalid reputation on "active_votes"

### ISSUE THREAD

**Issue by emre** [steemit/hivemind#175]
I was syncing my Hivemind node with `api.steemit.com`. While I was checking new posts, I saw the "active_votes" (`votes_csv` in hivemind terminology.) reporting 25 for every vote caster.

After some digging, I found out that the problem relies to the `api.steemit.com`.

**Steps to reproduce**

- Find a new content (created on yesterday, or today) and call `get_content` on api.steemit.com.

Example:

```
curl -s --data '{"jsonrpc":"2.0", "method":"condenser_api.get_content", "params":["emrebeyler", "witness-update-new-infrastructure-projects-and-statement-regarding-recent-incidents"], "id":1}' https://api.steemit.com
```

Check the `active_votes`:

```
"active_votes": [{
        "voter": "kaylinart",
        "weight": 69590,
        "rshares": "291880101717",
        "percent": 10000,
        "reputation": 0,
        "time": "2019-01-19T12:39:45"
    }, {
        "voter": "claudiop63",
        "weight": 411,
        "rshares": 3447378638,
        "percent": 10000,
        "reputation": 0,
        "time": "2019-01-19T12:50:57"
    },
    (...),],
```

All reputations are reported as `0`. Hivemind sees that and registers the reputation as 25 on the database.

This looks like it's not a direct Hivemind problem. Might be related to jussi. However, I don't know any other place to report it, so creating the issue, here.

**Comment by inertia186** [comment]
I have also observed this problem. Maybe `hivemind sync` should reject `api.steemit.com` or any node that is backed by Hivemind.

**Comment by nynhex** [comment]
@intertia186

i 🤔 this might work. 

cc: @roadscape

**Comment by nynhex** [comment]
i’ll look at this over the weekend to see if i have any visibility into whether it’s jussi or hive mind or both.

**Comment by roadscape** [comment]
Good catch. api.steemit.com nodes no longer run `follow_api`, but they do enable `reputation_api`. Probably `condenser_api.get_content` was not updated to leverage data from the new plugin.

And actually this is not directly a problem for hivemind, except there is a related bug: https://github.com/steemit/hivemind/issues/161

However, we really should question if we really want all this information stuffed into a single `get_content` call as it's already a lot.

**Comment by emre** [comment]
> And actually this is not directly a problem for hivemind, except there is a related bug: #161

Hivemind registers the reputation in a correct way based on the data source. (since `0` means `25`.) I wasn't sure where to open the issue, though.

> However, we really should question if we really want all this information stuffed into a single get_content call as it's already a lot.

Agreed. I have never seen somebody uses `reputation` on active_votes, however,`rshares`, `weight` and `voter` fields are used extensively in apps, bots, scripts.

As long as that change is announced beforehand with a removal notice, I think the correct way is getting the votes in a separate call.

**Comment by roadscape** [comment]
@emre I've filed an issue on the steem repo and added relevant details from your OP there: https://github.com/steemit/steem/issues/3240

Since the remaining portion of this issue is already covered in #161, I'm closing this one.
