### ISSUE TITLE
`condenser_api.get_blog` called with correct props returns an error

### ISSUE THREAD

**Issue by jakipatryk** [steemit/hivemind#186]
For example, with *start_entry_id=4* and *limit=8* I get:
```{"jsonrpc":"2.0","result":{"error":{"code":-32000,"message":"start_index and limit combination is invalid (4, 8) (hivemind-alpha)"}},"id":1}```

How to reproduce:
```
curl -s --data '{"jsonrpc":"2.0", "method":"condenser_api.get_blog", "params":["jakipatryk",4,8], "id":1}' https://api.steemit.com
```

**Comment by roadscape** [comment]
@jakipatryk based on my review of the steemd implementation, this is what I gathered was the intended behavior:

```
    (acct, 2) = returns blog entries 0 up to 2 (3 oldest)
    (acct, 0) = returns all blog entries (limit 0 means return all?)
    (acct, 2, 1) = returns 1 post starting at idx 2
    (acct, 2, 3) = returns 3 posts: idxs (2,1,0)
```

Params `(acct, 4, 8)` would then be requesting 8 posts starting at `idx=4`, and ending at `idx=-3` which doesn't make sense. Basically, `limit` should be less than or equal to `start_entry_id+1`. Does this make sense?

**Comment by jakipatryk** [comment]
@roadscape Actually, looks like `start_entry_id=4` and `limit=8` was not what I meant. It used to work like that:

```
# (account, startId, limit)
('acc', 0, 3) = returns blog entries 0 up to 3 (3 NEWEST)
     
# example response:
[
          {
            comment: {
              author: 'jakipatryk',
              body: '123'
            },
            blog: 'jakipatryk',
            reblog_on: '1970-01-01T00:00:00',
            entry_id: 103
          },
          {
            comment: {
              author: 'jacekw',
              body: '123'
            },
            blog: 'jakipatryk',
            reblog_on: '2018-07-16T13:09:39',
            entry_id: 102
          },
          {
            comment: {
              author: 'jakipatryk',
              body: '123'
            },
            blog: 'jakipatryk',
            reblog_on: '1970-01-01T00:00:00',
            entry_id: 101
          }
]
```

So the greater `entry_id` was, the newer the post was. Then:

```
# (account, startId, limit)
('acc', 100, 3) = returns 3 posts, ids: (100, 99, 98)
     
# example response:
[
          {
            comment: {
              author: 'jakipatryk',
              body: 'fdsgfdgsdgf'
            },
            blog: 'jakipatryk',
            reblog_on: '1970-01-01T00:00:00',
            entry_id: 100
          },
          {
            comment: {
              author: 'roadscape',
              body: '123'
            },
            blog: 'jakipatryk',
            reblog_on: '2018-07-16T13:09:39',
            entry_id: 99
          },
          {
            comment: {
              author: 'jakipatryk',
              body: 'blabla'
            },
            blog: 'jakipatryk',
            reblog_on: '1970-01-01T00:00:00',
            entry_id: 98
          }
]
```

[This function](https://github.com/jakipatryk/steeditor/blob/master/src/app/steem-rpc/services/steem-rpc.service.ts#L54-L95) in my app is using `condenser_api.get_blog`, and [there are the tests](https://github.com/jakipatryk/steeditor/blob/master/src/app/steem-rpc/services/steem-rpc.service.spec.ts#L93-L267).

So the inconsistency is that the steemd's version always return positive `entry_id`, and the Hivemind's version sometimes return negative `entry_id`s (when `start_id=0` and `limit>0`), which is useless because it doesn't provide information what is the real `entry_id` of this post, thus there is no way to load next (older) posts.

**Comment by roadscape** [comment]
@jakipatryk is the behavior only an issue with `start_id=0`? Do all other cases work as expected?

**Comment by jakipatryk** [comment]
@roadscape yeah, I think so

**Comment by roadscape** [comment]
@jakipatryk if the returned idx is the only issue, then https://github.com/steemit/hivemind/pull/228 should resolve it. This change returns the effective `start_index` to the idx enumerator (translating -1 to actual max_idx and leveraging it in the response).
