### ISSUE TITLE
Default LOG_LEVEL=INFO is showing WARNING messages

### ISSUE THREAD

**Issue by Jolly-Pirate** [steemit/hivemind#211]
The LOG_LEVEL is INFO by default, but it's showing WARNING messages too. According to https://docs.python.org/2/library/logging.html the WARNING level is higher than INFO, therefore it shouldn't show, if I'm not mistaken.

```
WARNING:hive.utils.stats:[STEEM][110ms] get_accounts[3] -- 3.7x par (11/3)
WARNING:hive.utils.stats:[STEEM][163ms] get_content[14] -- 1.5x par (6/4)
INFO:hive.indexer.sync:[LIVE] Got block 33427611 at 2019-06-01T20:22:48 --  27 txs,  1 posts,  0 edits,  2 payouts, 10 votes,  1 counts,  3 accts,  0 follows --  311ms
```

**Comment by roadscape** [comment]
Hi @Jolly-Pirate, the level which is set defines the *lowest* entries to show. So `INFO` is a bit spammier, showing `INFO`, `WARNING`, `ERROR`. Setting it to `WARNING` would only show `WARNING` and `ERROR`. `DEBUG` is the spammiest level.
