### ISSUE TITLE
Communities core [S1]

### ISSUE THREAD

**Issue by roadscape** [steemit/hivemind#214]
Ops to handle:
- [x] **registration**
- [x] **roles**
- [x] **metadata**
- [x] **subscriptions**
- [x] **posting** logic/validators

APIs:
  - [x] get community metadata
    - settings
    - display
    - leadership
    - viewer role
  - [x] get community trending/created
  - [x] get subscribed communities (& roles)

**Comment by scottjarvie** [comment]
You should consider adding this to the communities label.

**Comment by roadscape** [comment]
Posting validation includes two fields: `is_valid` and `is_muted`. Need to re-evaluate the usage/semantics and determine if a single field would suffice

**Comment by roadscape** [comment]
Continues in https://github.com/steemit/hivemind/issues/223
