### ISSUE TITLE
post erroneously marked deleted

### ISSUE THREAD

**Issue by roadscape** [steemit/hivemind#226]
`crystalliu/8azzlarj6um` in `hive_posts` shows `is_deleted=1` but is in fact available from steemd. Evaluate the cause and perform an audit.

**Comment by roadscape** [comment]
The comment was created in block [#35586624](https://steemd.com/b/35586624) then deleted **and** re-created in [#35586624](https://steemd.com/b/35586624).

```
+----------+----------------+
| block    | type           |
+----------+----------------+
| 35486821 | comment        |
| 35586624 | delete_comment |
| 35586624 | comment        |
| 35586626 | comment        |
| 35586631 | comment        |
| 35586634 | comment        |
| 35586796 | comment        |
| 35736482 | comment        |
| 35736485 | comment        |
| 35736491 | comment        |
| 35736496 | comment        |
| 35736499 | comment        |
| 35736502 | delete_comment |
| 35736502 | comment        |
| 35737064 | comment        |
| 35739655 | comment        |
| 35751174 | comment        |
| 35921239 | comment        |
+----------+----------------+
```

**Comment by quetzalcoatl** [comment]
yeah, crystalliu either has a serious bug in his scripts, or must have discovered that bug long while ago. There's a lot of delete/recreate (or just re-create w/o even deleting the previous one) operations on that account, with absolutely no changes to the posts' contents. Sometimes that happens on the same block, sometimes deletion is in one, and reposting in another block.

Aside from displaying the post as deleted on steemit, or causing unspecified 'error' on steemd, I think there's also some issue with tracking time.

This https://steemit.com/@crystalliu/8azzlarj6um displays as 'created 2019-08-21', whereas as you found out, original block 35486821 was at 2019-08-12.

Ruby, 
```
  require 'steem'
  api = Steem::CondenserApi.new
  pp api.get_content('crystalliu','8azzlarj6um').result
```
response (trimmed):
```
{"id"=>79300114,
 "author"=>"crystalliu",
 "permlink"=>"8azzlarj6um",
 "category"=>"dtube",
 "parent_author"=>"",
 "parent_permlink"=>"dtube",
 "title"=>"IMG 1199",
 "body"=>
  .........
 "last_update"=>"2019-08-21T04:21:18",
 "created"=>"2019-08-21T04:21:18",
 "active"=>"2019-08-27T14:33:06",
 "last_payout"=>"2019-08-28T04:21:18",
 "depth"=>0,
 "children"=>4,
```

Please note that `created` and `last_update` show the last creation time, so it seems that by deleting a post and then reposting it one can effectively "reset" its age. On steemit, I've seen some posts that were 'Created yesterday' with comments 14days old. Looks pretty strange and surely can fool some algorithms.

I'd say if comments and votes survive deletion and re-creation, then such delete&recreate should count as "edit" and preserve original timestamp, not as "create from scratch"?

OTOH, if delete&recreate counts as a new post, then old comments and votes should not be associated with the new post..
