### ISSUE TITLE
Add Migrations

### ISSUE THREAD

**Issue by Netherdrake** [steemit/hivemind#23]
I tried updating hive to the latest version, but the schema is out of date.

```
2017-09-28T10:24:00.298529363Z sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'is_valid' in 'field list'")
```

Could you please add db migrations, or at least publish a simple textfile with SQL required to upgrade /w dates or commit hashes?

**Comment by roadscape** [comment]
The schema is still undergoing a lot of changes, and the approach we're currently using is to simply reindex from scratch. (Most schema changes would require a replay anyway.) This is why the focus right now is on sync speed. We'll revisit migrations later.
