### ISSUE TITLE
Apart from api. steemit. com, are there any other steemd full nodes that can be used for synchronization?

### ISSUE THREAD

**Issue by dapp8coder** [steemit/hivemind#256]
Apart from api. steemit. com, are there any other steemd full nodes that can be used for synchronization?

in china,  api. steemit. com is banned

**Comment by jredbeard** [comment]
You might be able to use anyx.io @dapp8coder

**Comment by dapp8coder** [comment]
thanks,

**Comment by dapp8coder** [comment]
I have get a node what work well in china.
