### ISSUE TITLE
additional community props

### ISSUE THREAD

**Issue by roadscape** [steemit/hivemind#277]
- avatar
- cover image
- preferred view mode [list, blog, grid, photo]

**Comment by roadscape** [comment]
Update docs to reflect `settings` standard fields:
- `avatar_url`
- `cover_url`
- `default_view` = `list | blog | grid | photo` (specify intended client rendering)

**Comment by asgarth** [comment]
Is this something we can already use?

**Comment by roadscape** [comment]
@asgarth soon

**Comment by asgarth** [comment]
Can you share a sample of a community with the props?

**Comment by roadscape** [comment]
@asgarth `hive-171487`
