### ISSUE TITLE
some SQLAlchemy dialect-specific data types are preventing sqlite support

### ISSUE THREAD

**Issue by john-g-g** [steemit/hivemind#3]
Example from [hivemind/hive/db/schema.py](
https://github.com/steemit/hivemind/blob/b459f91d2b539076573ea0208e40c83a6796574c/hive/db/schema.py#L5)
```python
from sqlalchemy.dialects.mysql import (
    CHAR, SMALLINT, TINYINT,
    TINYTEXT, MEDIUMTEXT, DOUBLE,
)
```

**Comment by roadscape** [comment]
There's no plan to support sqlite. MySQL is the target for now, and at some point we may abstract out db layer to add Postgres.

**Comment by sneak** [comment]
i would love generic SQL/orm support - if we can support the subset of SQL that mysql, postgres, and sqlite all support - it would be nice to retain compatibility.

**Comment by roadscape** [comment]
superseded by #27
