### ISSUE TITLE
deploy hivemindsync to aws

### ISSUE THREAD

**Issue by roadscape** [steemit/hivemind#30]
We need a process which will periodically save db snapshots to be used for quickly launching new instances

- [x] hivesync service
- [x] hivesync full sync
- [x] get init time < 30 mins #108 
- [x] dev
- [x] stage
- [x] prod
- ~hive listeners/API servers in dev/stage/prod~ #109

**Comment by jredbeard** [comment]
Same issue / additional info: https://github.com/steemit/steempunks/issues/118

**Comment by roadscape** [comment]
`master` branch and `hivemind-47e185e0-latest.tar.lz4` is what we'll want to use for the new envs.

**Comment by jredbeard** [comment]
this is available and working now in dev/stage/prod
