### ISSUE TITLE
bridge.get_discussion returns incorrect data

### ISSUE THREAD

**Issue by only-dev-time** [steemit/hivemind#329]
I'm opening an issue for the problem that has existed for some time in order to discuss and solve it.

The data displayed by Steemit [Condenser](https://github.com/steemit/condenser) (from the api.steemit.com node) are incorrect:
![grafik](https://github.com/steemit/hivemind/assets/111915936/a79afb6d-5322-4c69-acbf-34f3cd371acc)

It should look like this (from the node api.moecki.online and api.steemitdev.com):
![grafik](https://github.com/steemit/hivemind/assets/111915936/3f6a668c-bb3d-44a2-8f41-a3c0e5f246f0)

The Condenser receives the data through the request `bridge.get_discussion`. This is the example:
`{"jsonrpc":"2.0", "method":"bridge.get_discussion", "params":["germansailor", "power-up"], "id":1}`

The main differences are:
| field | api.steemit.com (incorrect) | api.moecki.online (correct) |
|-|-|-|
|children|0|11|
|stats.total_votes|18|51|

But the field `replies` from api.steemit.com is correct:
`"replies":["weisser-rabe/s9osmw","moecki/s9ounw","boomerang/re-power-up-20240302t000400","steemcurator04/s9pst0","don-t/s9px6h"]`

**Comment by only-dev-time** [comment]
I don't know what has already been analysed to localise the problem. I have done a little research myself to see what might be possible.

- As far as I could determine, no cached database queries are used when executing `get_discussion`. 
- After the `post_ids` of all child posts have been [determined](https://github.com/steemit/hivemind/blob/9ee7c496ac579d1d5d9b042215811773a5381ee3/hive/server/bridge_api/thread.py#L75), the post data are [loaded](https://github.com/steemit/hivemind/blob/9ee7c496ac579d1d5d9b042215811773a5381ee3/hive/server/bridge_api/objects.py#L40) from the `hive_posts_cache` table.

At this point, it should be checked which entries the fields specified above for the post from the example (`post_id = 107110396`) have in the table on api.steemit.com. Does it already contain the incorrect data? 
If so, this would indicate a sync/recount error that we could investigate further. In that case, I have a suspicion...

**Comment by only-dev-time** [comment]
Since I have not yet received an answer to my above question, I have looked at the processing of the operations. 

At various points in the Hivemind code, batch requests are sent to the `steemd_url`. 
For example with `condenser_api-get_content`: `[{"jsonrpc": "2.0", "id":1, "method": "condenser_api. get_content","params":["remlaps","re-moecki-202437t19729701z"]}, {"jsonrpc":"2.0","id":2,"method":"condenser_api.get_content","params":["michelangelo3","sa1m6v"]}]`

These queries are rejected by api.steemit.com. However, not from the RPC node, but from the upstream OpenResty. If these queries are not processed and answered, Hivemind cannot fully synchronise the operations. I don't know how the servers are connected (internal addresses or public ones) and the queries run between the Hivemind node and the RPC node, for example. This should certainly not be discussed publicly here.
In any case, the settings should definitely be checked (if it has not already been done). 
I'm waiting for a feedback...

**Comment by ety001** [comment]
The issue has been fixed. Because the Steemd node which is used to support blockchain data to hivemind is full of disk.
So the sync progress is not running correctly.
