### ISSUE TITLE
community implementation

### ISSUE THREAD

**Issue by roadscape** [steemit/hivemind#34]
- [ ] creation op
 - [ ] custom ops, verify auths
 - [ ] API methods
   - get_community(name): admins, mods, descriptions, settings
   - list_communities(start, sort) (name/trending/subs)
   - list_tags(start, sort) (trending)
   - list_blogs(start, sort)
   - get_user_subscriptions(account, start, sort)
   - search: tag/user/community/title
   - (more)
- [ ] internal methods
   - top authors in community (trending)
   - top curators in community
   - top blogs
   - next 24h reward pool
   - community rank
- [ ] frontend
- [ ] test/profile
- [ ] steemit.com "global" acct (subs, follows, mutes?)

bonus
 - daily stats: subs, rank
   - top authors (d/w/m)

evaluate:
 - `self` as null-comm? allows sub to trending blogs
   - does this impact blog-follow?

**Comment by scottjarvie** [comment]
This is from 2017 seems like there is a similar ticket open that references API and all that stuff which was recently worked on today by @roadscape ... does this ticket still need to be around?
Also this label is confusing compared to the other label of project/communities

**Comment by roadscape** [comment]
Closing as outdated
