### ISSUE TITLE
env vars

### ISSUE THREAD

**Issue by roadscape** [steemit/hivemind#47]
Where to use env vars vs. args?

 - appbase flag
 - consistent use of db_url
 - steemd vs jussi flag

**Comment by roadscape** [comment]
- trail_blocks
 - max_block_num_diff?

**Comment by sneak** [comment]
Assume that the only knobs that will be available to a sysadmin will be env vars.  Args are only useful for someone manually running from the command line, which should be infrequent.

**Comment by sneak** [comment]
Reminder: being able to be used without jussi is not a design goal for hivemind.

**Comment by goldibex** [comment]
i would strongly advise just using configargparser, it handles all this for you, you get flags and env vars together for free

**Comment by roadscape** [comment]
Current vars:

 - `DATABASE_URL=postgresql://user:pass@localhost:5432/hive`
 - `STEEMD_URL=https://api.steemit.com`
 - `MAX_WORKERS=1` (recommended to use `1` until #71)
 - `MAX_BATCH=500` (optimal value?)
 - `LOG_LEVEL=INFO`

Pending:

 - `TRAIL_BLOCKS` (max_diff is redundant; healthy = no more than 1 behind trail)

**Comment by roadscape** [comment]
TRAIL_BLOCKS=-1 should be a signal to use last_irreversible
