### ISSUE TITLE
appbase tasks

### ISSUE THREAD

**Issue by roadscape** [steemit/hivemind#73]
- appbase has new error responses, breaking http_client assumptions.
   - causing some appbase errors to not result in retry
 - remove appbase flag if launched before 1.0

**Comment by mvandeberg** [comment]
I want to verify this is not a bug in appbase.

All errors in appbase should result in a valid JSONRPC response and never return an http error unless the original request was not valid http. All errors should match the JSONRPC 2.0 spec.

If you are observing behavior different than what I described above, it is unintentional and likely an appbase bug.

**Comment by roadscape** [comment]
What I'm seeing is that when running against appbase, HttpClient fails to retry on some errors (non-appbase testing has not encountered any such condition in a long time).

The last case I saw was along the lines of "Failed to acquire lock", included in the `error` key of the response. It seems HttpClient has never handled this case. Perhaps pre-appbase it was caught earlier due to a different HTTP response code?

I know the `error` key in response is not new, so I need to further study the flow of errors/exceptions as they are handled in http_client.py to figure out why this case is only occurring now.

**Comment by mvandeberg** [comment]
For appbase, I would base your response on the error code.

I am guessing part of the problem is that JSONRPC errors are now spec compliant. They weren't necessarily prior to appbase.
