### ISSUE TITLE
prevent backwards block drift

### ISSUE THREAD

**Issue by roadscape** [steemit/hivemind#79]
I suspect it's possible to fall behind head_block and never catch up. A simple solution is to change the interval to 2.9s or so to keep it eager. A more robust solution is to use block timestamps to (a) detect missed slots, and (b) line up local slots.

**Comment by roadscape** [comment]
Under stable conditions the drift is up to 1-2 blocks per 24h.

**Comment by sneak** [comment]
1s interval is fine, jussi caches GDGP - that’s the one it uses, right?

**Comment by inertia186** [comment]
You can scale the interval depending on how far behind it us.  Radiator's stream does this and it allows it to catch up even when it's more than 2000 blocks behind.

**Comment by roadscape** [comment]
Once caught up to head, hive polls for the next block in 3s intervals. The behavior used to be that if it was not available, to delay by 1s and try again (quite rare). Usually it's due to missed blocks and it handles as expected. But sometimes it's due to server error, and this caused drift. The change was to change schedule only based on missed blocks and never on server error.
