### ISSUE TITLE
promoted payments tracking

### ISSUE THREAD

**Issue by roadscape** [steemit/hivemind#80]
It turns out tracking 'promoted' value is done in the `tags` plugin, so this is something that either needs to be moved into its own steem plugin, or needs to be taken over by hive.

https://github.com/steemit/steem/blob/8cd5f688d75092298bcffaa48a543ed9b01447a6/libraries/plugins/tags/tags_plugin.cpp#L392

**Comment by mvandeberg** [comment]
Preferably by Hivemind. Promoted is just one of the indices on the tag objects. We don't get nearly the state savings if we keep it in steemd.
