### ISSUE TITLE
API stress testing

### ISSUE THREAD

**Issue by roadscape** [steemit/hivemind#93]
Once deployed on AWS (#30):

- [x] load test raw APIs
- [x] attack raw APIs
- [x] load test APIs via condenser
- [x] add indexes as needed
- [x] add caching as needed
- [x] testing other clients against hive API

**Comment by goldibex** [comment]
Blocked by #30.

**Comment by roadscape** [comment]
Completed in https://github.com/steemit/hivemind/pull/163
