### ISSUE TITLE
initial sync performance

### ISSUE THREAD

**Issue by roadscape** [steemit/hivemind#95]
If initial sync performance is not sufficient here are some approaches to evaluate:

- [x] disable indexes during initial sync
- [x] disable constraints during initial sync
- [ ] more multi-row inserts (which tables?)
- [x] more mem caching
- [ ] smarter batching of write queries to pg
- [ ] parallel fetch #68 
- [ ] batching workers #71 
- [ ] async httpclient #90 
- [ ] deferring of constraints (see https://github.com/steemit/hivemind/issues/52#issuecomment-354487006)
- [ ] additional pg [config](https://www.postgresql.org/docs/9.4/static/runtime-config-resource.html) tuning (previous work in #52)

Insight into this issue is somewhat constrained until #30 is complete. 

---

https://github.com/steemit/hivemind/issues/37#issuecomment-369039408 contains reference measurements for initial block sync. This issue branched from #52.

**Comment by hernandev** [comment]
is it taking like many days for initial sync normal?

**Comment by roadscape** [comment]
Yes, it's normal. We're running tests now to check performance, but I don't think it can be faster than 1-2 days. Our plan is to have a snapshot service which regularly dumps db so we can boot new instances quickly.

**Comment by hernandev** [comment]
@roadscape it just now finished syncing, can you give me an estimate on how big is a snapshot would be?

just to validate if my setup if parsing it correctly.

I can provide the snapshots, unofficially for now.

**Comment by roadscape** [comment]
@hernandev my Postgres data dir is ~144G; breakdown by table:

```
    table_name    |   rows   | total_size | index_size | toast_size | table_size | total_per_row | index_per_row | table_per_row
------------------+----------+------------+------------+------------+------------+---------------+---------------+---------------
 hive_posts_cache | 39960128 | 101 GB     | 5799 MB    | 39 GB      | 56 GB      | 2713 bytes    | 152 bytes     | 1511 bytes
 hive_posts       | 34449752 | 15 GB      | 9046 MB    | 8192 bytes | 6117 MB    | 461 bytes     | 275 bytes     | 186 bytes
 hive_accounts    |  1517265 | 8719 MB    | 494 MB     | 26 MB      | 8198 MB    | 6025 bytes    | 341 bytes     | 5665 bytes
 hive_follows     | 51270044 | 6573 MB    | 3996 MB    |            | 2578 MB    | 134 bytes     | 81 bytes      | 52 bytes
 hive_blocks      | 20470916 | 4388 MB    | 1765 MB    |            | 2623 MB    | 224 bytes     | 90 bytes      | 134 bytes
 hive_post_tags   | 26925714 | 4314 MB    | 3134 MB    |            | 1180 MB    | 167 bytes     | 122 bytes     | 45 bytes
 hive_feed_cache  | 11299114 | 1319 MB    | 839 MB     |            | 481 MB     | 122 bytes     | 77 bytes      | 44 bytes
 hive_reblogs     |  3289994 | 506 MB     | 321 MB     |            | 185 MB     | 161 bytes     | 102 bytes     | 59 bytes
 hive_payments    |    10535 | 1000 kB    | 256 kB     |            | 744 kB     | 97 bytes      | 24 bytes      | 72 bytes
 hive_state       |        1 | 128 kB     | 56 kB      | 8192 bytes | 64 kB      | 128 kB        | 56 kB         | 64 kB
```

**Comment by hernandev** [comment]
thank you very much @roadscape, posts_cache table will not automatically be populated unless I make queries against the API, did I got this correctly?

**Comment by roadscape** [comment]
Initial block sync w/ untuned postgres on i3.large: 81hrs, 34m. Writes dominate after 12.5M blocks:

![image](https://user-images.githubusercontent.com/5168676/37364147-aeee53e6-26c7-11e8-9cd5-4f95eca1610c.png)

**Comment by roadscape** [comment]
@hernandev the posts_cache table should be populated immediately after hive_blocks as part of the initial sync routine. There is a bug #98 which causes the process to stop early; restarting `hive sync` will resume initial population of the post cache. Also please be aware I may delete some comments from this thread just to keep it tidy and focused; you are more than welcome to open new issues if you are having problems with hive. I appreciate you taking the time to test this software.

**Comment by hernandev** [comment]
@roadscape you provided me all info I needed. thank you, and of course, feel free to clean it up.

thank you!

**Comment by roadscape** [comment]
Peak memory usage during block index is ~983mb. After first batch of 1M posts, 1485mb. Looks like assumption of 2GB max memory usage during init sync will hold.

![image](https://user-images.githubusercontent.com/5168676/37369202-6d0999a4-26d6-11e8-97cb-06e3fbe01e75.png)

**Comment by roadscape** [comment]
The first 1M posts were processed in approx 2441s, averaging 410/s. Assuming a constant rate it would take 25.3hrs to index all 37,299,891 posts.

**Comment by roadscape** [comment]
![image](https://user-images.githubusercontent.com/5168676/37424280-190d9662-278e-11e8-9581-a7683883327d.png)

![image](https://user-images.githubusercontent.com/5168676/37424540-aa127056-278e-11e8-83c3-8c7891e8710f.png)

**Comment by roadscape** [comment]
1. Follows handling accounts: up to 50% of SQL time
   - querying current state is most expensive; implement mem cache
   - inserts should be batched (necessitates tracking pending state); change PK to AI?
     - during init sync disable `hive_follows_ix2` and `hive_follows_ix3`
2. Post inserts: 20%
   - check if columns can be removed (category, depth)
   - during init sync disable `hive_posts_ix1` and `hive_posts_ix2`
   - consider merging `author+permlink` to `url`
3. Post id lookups: ~15%
   - increase LRU cache capacity from 1M to 2-4M (~500MB memory used per 1M entries)
4. Community lookup: 7%
   - disable entirely until block X

**Comment by roadscape** [comment]
Seeing peak memory reach 10GB during post sync.

**Comment by roadscape** [comment]
Initial pass complete; further opportunities should be created as new issues. Will evaluate further with next uninterrupted sync.
